name: Generate readme

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  generate-readme:
    runs-on: ubuntu-latest
    env:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Generate readme
        run: |
          yarn
          yarn generate-readme
